---
- name: Run Temp Check Script
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Run Temp Check Script
      shell: vcgencmd measure_temp
      register: script_output
      changed_when: false  # Mark the task as unchanged, even if the command returns a non-zero exit code

    - name: Display Script Output
      debug:
        var: script_output.stdout | string  # Convert the stdout value to a string
